Repository HiMamaInc/bambora-client, pull requests merged in 2019-11, with the labels that each got.

#8 Streamline `Bambora::V1::ProfileResource` initialization
  README.md
  lib/bambora/v1/profile_resource.rb
  spec/bambora/v1/profile_resource_spec.rb
Labels: documentation, enhancement

#9 Renaming make_payment to create & adding alias
  README.md
  lib/bambora/v1/payment_resource.rb
  spec/bambora/v1/payment_resource_spec.rb
Labels: documentation

#12 Changing Class names so bundler auto-requires gem
  README.md
  bambora-client.gemspec
  lib/bambora.rb
  lib/bambora/client.rb
  lib/bambora/client/version.rb
  lib/bambora/json_client.rb
  lib/bambora/rest_client.rb
  lib/bambora/v1/profile_resource.rb
  spec/bambora/client_spec.rb
  spec/bambora/json_client_spec.rb
  spec/bambora/rest_client_spec.rb
  spec/bambora_spec.rb
  spec/spec_helper.rb
Labels: documentation, enhancement

#13 Adding Clients and Adapters for Legacy APIs
  .ruby-version
  Gemfile.lock
  bambora-client.gemspec
  bin/console
  lib/bambora/adapters/json_response.rb
  lib/bambora/adapters/query_string_response.rb
  lib/bambora/adapters/response.rb
  lib/bambora/client.rb
  lib/bambora/factories/response_adapter_factory.rb
  lib/bambora/headers.rb
  lib/bambora/json_client.rb
  lib/bambora/rest_client.rb
  lib/bambora/v1/profile_resource.rb
  lib/bambora/www_form_client.rb
  lib/bambora/www_form_parameters.rb
  lib/bambora/xml_client.rb
  lib/bambora/xml_request_body.rb
  spec/bambora/adapters/json_response_spec.rb
  spec/bambora/adapters/query_string_response_spec.rb
  spec/bambora/client_spec.rb
  spec/bambora/factories/response_adapter_factory_spec.rb
  spec/bambora/headers_spec.rb
  spec/bambora/json_client_spec.rb
  spec/bambora/v1/payment_resource_spec.rb
  spec/bambora/v1/profile_resource_spec.rb
  spec/bambora/www_form_client_spec.rb
  spec/bambora/xml_client_spec.rb
  spec/bambora/xml_request_body_spec.rb
  spec/support/shared_examples/json_response_parser_spec.rb
Labels: enhancement
