Repository HiMamaInc/bambora-client, pull requests merged in 2020-05, with the labels that each got.

#37 Implement payment profile retrieval method
  CHANGELOG.md
  Gemfile.lock
  lib/bambora/client/version.rb
  lib/bambora/v1/profile_resource.rb
  spec/bambora/v1/profile_resource_spec.rb
Labels: enhancement

#38 Remove `Gemfile.lock` from the codebase
  .gitignore
  Gemfile.lock
Labels: dependencies

#39 Implement method to update a credit card and bank account payment profile
  CHANGELOG.md
  README.md
  lib/bambora/client/version.rb
  lib/bambora/rest/client.rb
  lib/bambora/rest/json_client.rb
  lib/bambora/v1/profile_resource.rb
  spec/bambora/rest/json_client_spec.rb
  spec/bambora/v1/profile_resource_spec.rb
Labels: documentation, enhancement
